services:
  mongodb:
    image: mongo:3.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    restart: always
    ports: 
      - 27017:27017
  api: 
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_URI=
    ports:
      - 8080:8080

